version: "3.7"
services:
  youtube-dl:
    image: qmcgaw/youtube-dl-alpine
    container_name: youtube-dl
    network_mode: bridge
    volumes:
      - ./downloads:/downloads
    command: |
      https://www.youtube.com/watch?v=HagVnWAeGcM
      -o "/downloads/%(title)s-%(duration)s.%(ext)s"
